# 修改hostname
# review test 
# branch f1 
name: GitHub Actions for ci  

on:
  #pull_request:
  #  branches:
  #    - master
  push:
     branches:
       - f1

jobs:
  cijob:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
         java-version: 1.8

    - name: Maven Compile
      run: mvn compile

    - name: Maven Testing
      run: mvn test





